[tox]
envlist = py{310,311,312,313}-qiskit{1,2}, lint, docs

[gh-actions]
python =
  3.10: py310-qiskit1, py310-qiskit2
  3.11: py311-qiskit1, py311-qiskit2
  3.12: py312-qiskit1, py312-qiskit2
  3.13: py313-qiskit1, py313-qiskit2

[testenv]
deps =
  qiskit1: qiskit[qasm3-import]>=1.0.0,<2.0.0
  qiskit2: qiskit[qasm3-import]>=2.0.0,<3.0.0
  .[test]
  -r requirements.txt
  -r requirements-test.txt
usedevelop = true
setenv =
  VIRTUAL_ENV={envdir}
  LANGUAGE=en_US
  LC_ALL=en_US.utf-8
commands = pytest --cov=qiskit_ionq --cov-report=term-missing --cov-fail-under=80

[testenv:lint]
deps =
  pylint
  -r requirements.txt
  -r requirements-test.txt
commands =
  pylint -rn --rcfile={toxinidir}/.pylintrc qiskit_ionq test
  python tools/verify_headers.py qiskit_ionq test

[testenv:docs]
allowlist_externals = make
envdir = .tox/docs
deps =
  -r requirements-docs.txt
commands = make html

[pytest]
filterwarnings =
  error::DeprecationWarning
  error::PendingDeprecationWarning
  ignore:The method .*MCXGate.get_num_ancilla_qubits.*:PendingDeprecationWarning
  ignore:The class .*MCX.*:PendingDeprecationWarning
  ignore:The property .*Instruction.condition.*:DeprecationWarning
  ignore:Failed to get qubits .* Using 4:UserWarning:qiskit_ionq\.helpers
  ignore:Retrying .* more time\(s\) after .*:UserWarning:qiskit_ionq\.helpers
  ignore:TimedOut:UserWarning:qiskit_ionq\.ionq_job
  ignore:The parameter\(s\).*not checked by default.*submitted in the request\.:UserWarning:qiskit_ionq\.ionq_client
  ignore:Unable to retrieve result for job .* cancelled:UserWarning:qiskit_ionq\.ionq_job
  ignore:All qubits are idle, removing all but the first\.:UserWarning:test\.transpile_ionq_gates\.test_transpile_ionq_gates
  ignore:Transpiler default optimization_level=2\. IonQ \(QIS\) recommends 0-1.*:Warning:qiskit_ionq\.ionq_backend
