---
name: Docs Publish
on:
  workflow_dispatch:
  push:
    tags:
      - "*"


jobs:
  deploy:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: setup-uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.13"
    - name: Install system dependencies
      run: sudo apt-get install -y graphviz pandoc
    - name: Install requirements
      run: uv sync --locked --no-default-groups --group docs
    - name: Build docs
      run: uv run --no-sync make html
    - name: Bypass Jekyll Processing # Necessary for setting the correct css path
      run: touch build/html/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/html/
